# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mrlukasbos/development/Chess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mrlukasbos/development/Chess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mrlukasbos/development/Chess/CMakeFiles /Users/mrlukasbos/development/Chess/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mrlukasbos/development/Chess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Chess

# Build rule for target.
Chess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Chess
.PHONY : Chess

# fast build rule for target.
Chess/fast:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/build
.PHONY : Chess/fast

Board.o: Board.cpp.o

.PHONY : Board.o

# target to build an object file
Board.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Board.cpp.o
.PHONY : Board.cpp.o

Board.i: Board.cpp.i

.PHONY : Board.i

# target to preprocess a source file
Board.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Board.cpp.i
.PHONY : Board.cpp.i

Board.s: Board.cpp.s

.PHONY : Board.s

# target to generate assembly for a file
Board.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Board.cpp.s
.PHONY : Board.cpp.s

ChessPiece.o: ChessPiece.cpp.o

.PHONY : ChessPiece.o

# target to build an object file
ChessPiece.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/ChessPiece.cpp.o
.PHONY : ChessPiece.cpp.o

ChessPiece.i: ChessPiece.cpp.i

.PHONY : ChessPiece.i

# target to preprocess a source file
ChessPiece.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/ChessPiece.cpp.i
.PHONY : ChessPiece.cpp.i

ChessPiece.s: ChessPiece.cpp.s

.PHONY : ChessPiece.s

# target to generate assembly for a file
ChessPiece.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/ChessPiece.cpp.s
.PHONY : ChessPiece.cpp.s

Interface.o: Interface.cpp.o

.PHONY : Interface.o

# target to build an object file
Interface.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Interface.cpp.o
.PHONY : Interface.cpp.o

Interface.i: Interface.cpp.i

.PHONY : Interface.i

# target to preprocess a source file
Interface.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Interface.cpp.i
.PHONY : Interface.cpp.i

Interface.s: Interface.cpp.s

.PHONY : Interface.s

# target to generate assembly for a file
Interface.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Interface.cpp.s
.PHONY : Interface.cpp.s

Move.o: Move.cpp.o

.PHONY : Move.o

# target to build an object file
Move.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Move.cpp.o
.PHONY : Move.cpp.o

Move.i: Move.cpp.i

.PHONY : Move.i

# target to preprocess a source file
Move.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Move.cpp.i
.PHONY : Move.cpp.i

Move.s: Move.cpp.s

.PHONY : Move.s

# target to generate assembly for a file
Move.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Move.cpp.s
.PHONY : Move.cpp.s

PieceColor.o: PieceColor.cpp.o

.PHONY : PieceColor.o

# target to build an object file
PieceColor.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/PieceColor.cpp.o
.PHONY : PieceColor.cpp.o

PieceColor.i: PieceColor.cpp.i

.PHONY : PieceColor.i

# target to preprocess a source file
PieceColor.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/PieceColor.cpp.i
.PHONY : PieceColor.cpp.i

PieceColor.s: PieceColor.cpp.s

.PHONY : PieceColor.s

# target to generate assembly for a file
PieceColor.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/PieceColor.cpp.s
.PHONY : PieceColor.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Player.cpp.s
.PHONY : Player.cpp.s

Square.o: Square.cpp.o

.PHONY : Square.o

# target to build an object file
Square.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Square.cpp.o
.PHONY : Square.cpp.o

Square.i: Square.cpp.i

.PHONY : Square.i

# target to preprocess a source file
Square.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Square.cpp.i
.PHONY : Square.cpp.i

Square.s: Square.cpp.s

.PHONY : Square.s

# target to generate assembly for a file
Square.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/Square.cpp.s
.PHONY : Square.cpp.s

chesspieces/Bishop.o: chesspieces/Bishop.cpp.o

.PHONY : chesspieces/Bishop.o

# target to build an object file
chesspieces/Bishop.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Bishop.cpp.o
.PHONY : chesspieces/Bishop.cpp.o

chesspieces/Bishop.i: chesspieces/Bishop.cpp.i

.PHONY : chesspieces/Bishop.i

# target to preprocess a source file
chesspieces/Bishop.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Bishop.cpp.i
.PHONY : chesspieces/Bishop.cpp.i

chesspieces/Bishop.s: chesspieces/Bishop.cpp.s

.PHONY : chesspieces/Bishop.s

# target to generate assembly for a file
chesspieces/Bishop.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Bishop.cpp.s
.PHONY : chesspieces/Bishop.cpp.s

chesspieces/King.o: chesspieces/King.cpp.o

.PHONY : chesspieces/King.o

# target to build an object file
chesspieces/King.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/King.cpp.o
.PHONY : chesspieces/King.cpp.o

chesspieces/King.i: chesspieces/King.cpp.i

.PHONY : chesspieces/King.i

# target to preprocess a source file
chesspieces/King.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/King.cpp.i
.PHONY : chesspieces/King.cpp.i

chesspieces/King.s: chesspieces/King.cpp.s

.PHONY : chesspieces/King.s

# target to generate assembly for a file
chesspieces/King.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/King.cpp.s
.PHONY : chesspieces/King.cpp.s

chesspieces/Knight.o: chesspieces/Knight.cpp.o

.PHONY : chesspieces/Knight.o

# target to build an object file
chesspieces/Knight.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Knight.cpp.o
.PHONY : chesspieces/Knight.cpp.o

chesspieces/Knight.i: chesspieces/Knight.cpp.i

.PHONY : chesspieces/Knight.i

# target to preprocess a source file
chesspieces/Knight.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Knight.cpp.i
.PHONY : chesspieces/Knight.cpp.i

chesspieces/Knight.s: chesspieces/Knight.cpp.s

.PHONY : chesspieces/Knight.s

# target to generate assembly for a file
chesspieces/Knight.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Knight.cpp.s
.PHONY : chesspieces/Knight.cpp.s

chesspieces/Pawn.o: chesspieces/Pawn.cpp.o

.PHONY : chesspieces/Pawn.o

# target to build an object file
chesspieces/Pawn.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Pawn.cpp.o
.PHONY : chesspieces/Pawn.cpp.o

chesspieces/Pawn.i: chesspieces/Pawn.cpp.i

.PHONY : chesspieces/Pawn.i

# target to preprocess a source file
chesspieces/Pawn.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Pawn.cpp.i
.PHONY : chesspieces/Pawn.cpp.i

chesspieces/Pawn.s: chesspieces/Pawn.cpp.s

.PHONY : chesspieces/Pawn.s

# target to generate assembly for a file
chesspieces/Pawn.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Pawn.cpp.s
.PHONY : chesspieces/Pawn.cpp.s

chesspieces/Queen.o: chesspieces/Queen.cpp.o

.PHONY : chesspieces/Queen.o

# target to build an object file
chesspieces/Queen.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Queen.cpp.o
.PHONY : chesspieces/Queen.cpp.o

chesspieces/Queen.i: chesspieces/Queen.cpp.i

.PHONY : chesspieces/Queen.i

# target to preprocess a source file
chesspieces/Queen.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Queen.cpp.i
.PHONY : chesspieces/Queen.cpp.i

chesspieces/Queen.s: chesspieces/Queen.cpp.s

.PHONY : chesspieces/Queen.s

# target to generate assembly for a file
chesspieces/Queen.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Queen.cpp.s
.PHONY : chesspieces/Queen.cpp.s

chesspieces/Rook.o: chesspieces/Rook.cpp.o

.PHONY : chesspieces/Rook.o

# target to build an object file
chesspieces/Rook.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Rook.cpp.o
.PHONY : chesspieces/Rook.cpp.o

chesspieces/Rook.i: chesspieces/Rook.cpp.i

.PHONY : chesspieces/Rook.i

# target to preprocess a source file
chesspieces/Rook.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Rook.cpp.i
.PHONY : chesspieces/Rook.cpp.i

chesspieces/Rook.s: chesspieces/Rook.cpp.s

.PHONY : chesspieces/Rook.s

# target to generate assembly for a file
chesspieces/Rook.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/chesspieces/Rook.cpp.s
.PHONY : chesspieces/Rook.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/main.cpp.s
.PHONY : main.cpp.s

players/HumanPlayer.o: players/HumanPlayer.cpp.o

.PHONY : players/HumanPlayer.o

# target to build an object file
players/HumanPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/HumanPlayer.cpp.o
.PHONY : players/HumanPlayer.cpp.o

players/HumanPlayer.i: players/HumanPlayer.cpp.i

.PHONY : players/HumanPlayer.i

# target to preprocess a source file
players/HumanPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/HumanPlayer.cpp.i
.PHONY : players/HumanPlayer.cpp.i

players/HumanPlayer.s: players/HumanPlayer.cpp.s

.PHONY : players/HumanPlayer.s

# target to generate assembly for a file
players/HumanPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/HumanPlayer.cpp.s
.PHONY : players/HumanPlayer.cpp.s

players/HybridPlayer.o: players/HybridPlayer.cpp.o

.PHONY : players/HybridPlayer.o

# target to build an object file
players/HybridPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/HybridPlayer.cpp.o
.PHONY : players/HybridPlayer.cpp.o

players/HybridPlayer.i: players/HybridPlayer.cpp.i

.PHONY : players/HybridPlayer.i

# target to preprocess a source file
players/HybridPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/HybridPlayer.cpp.i
.PHONY : players/HybridPlayer.cpp.i

players/HybridPlayer.s: players/HybridPlayer.cpp.s

.PHONY : players/HybridPlayer.s

# target to generate assembly for a file
players/HybridPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/HybridPlayer.cpp.s
.PHONY : players/HybridPlayer.cpp.s

players/MinMaxPlayer.o: players/MinMaxPlayer.cpp.o

.PHONY : players/MinMaxPlayer.o

# target to build an object file
players/MinMaxPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/MinMaxPlayer.cpp.o
.PHONY : players/MinMaxPlayer.cpp.o

players/MinMaxPlayer.i: players/MinMaxPlayer.cpp.i

.PHONY : players/MinMaxPlayer.i

# target to preprocess a source file
players/MinMaxPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/MinMaxPlayer.cpp.i
.PHONY : players/MinMaxPlayer.cpp.i

players/MinMaxPlayer.s: players/MinMaxPlayer.cpp.s

.PHONY : players/MinMaxPlayer.s

# target to generate assembly for a file
players/MinMaxPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/MinMaxPlayer.cpp.s
.PHONY : players/MinMaxPlayer.cpp.s

players/MonteCarloPlayer.o: players/MonteCarloPlayer.cpp.o

.PHONY : players/MonteCarloPlayer.o

# target to build an object file
players/MonteCarloPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/MonteCarloPlayer.cpp.o
.PHONY : players/MonteCarloPlayer.cpp.o

players/MonteCarloPlayer.i: players/MonteCarloPlayer.cpp.i

.PHONY : players/MonteCarloPlayer.i

# target to preprocess a source file
players/MonteCarloPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/MonteCarloPlayer.cpp.i
.PHONY : players/MonteCarloPlayer.cpp.i

players/MonteCarloPlayer.s: players/MonteCarloPlayer.cpp.s

.PHONY : players/MonteCarloPlayer.s

# target to generate assembly for a file
players/MonteCarloPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/MonteCarloPlayer.cpp.s
.PHONY : players/MonteCarloPlayer.cpp.s

players/RandomPlayer.o: players/RandomPlayer.cpp.o

.PHONY : players/RandomPlayer.o

# target to build an object file
players/RandomPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/RandomPlayer.cpp.o
.PHONY : players/RandomPlayer.cpp.o

players/RandomPlayer.i: players/RandomPlayer.cpp.i

.PHONY : players/RandomPlayer.i

# target to preprocess a source file
players/RandomPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/RandomPlayer.cpp.i
.PHONY : players/RandomPlayer.cpp.i

players/RandomPlayer.s: players/RandomPlayer.cpp.s

.PHONY : players/RandomPlayer.s

# target to generate assembly for a file
players/RandomPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/players/RandomPlayer.cpp.s
.PHONY : players/RandomPlayer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Chess"
	@echo "... Board.o"
	@echo "... Board.i"
	@echo "... Board.s"
	@echo "... ChessPiece.o"
	@echo "... ChessPiece.i"
	@echo "... ChessPiece.s"
	@echo "... Interface.o"
	@echo "... Interface.i"
	@echo "... Interface.s"
	@echo "... Move.o"
	@echo "... Move.i"
	@echo "... Move.s"
	@echo "... PieceColor.o"
	@echo "... PieceColor.i"
	@echo "... PieceColor.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Square.o"
	@echo "... Square.i"
	@echo "... Square.s"
	@echo "... chesspieces/Bishop.o"
	@echo "... chesspieces/Bishop.i"
	@echo "... chesspieces/Bishop.s"
	@echo "... chesspieces/King.o"
	@echo "... chesspieces/King.i"
	@echo "... chesspieces/King.s"
	@echo "... chesspieces/Knight.o"
	@echo "... chesspieces/Knight.i"
	@echo "... chesspieces/Knight.s"
	@echo "... chesspieces/Pawn.o"
	@echo "... chesspieces/Pawn.i"
	@echo "... chesspieces/Pawn.s"
	@echo "... chesspieces/Queen.o"
	@echo "... chesspieces/Queen.i"
	@echo "... chesspieces/Queen.s"
	@echo "... chesspieces/Rook.o"
	@echo "... chesspieces/Rook.i"
	@echo "... chesspieces/Rook.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... players/HumanPlayer.o"
	@echo "... players/HumanPlayer.i"
	@echo "... players/HumanPlayer.s"
	@echo "... players/HybridPlayer.o"
	@echo "... players/HybridPlayer.i"
	@echo "... players/HybridPlayer.s"
	@echo "... players/MinMaxPlayer.o"
	@echo "... players/MinMaxPlayer.i"
	@echo "... players/MinMaxPlayer.s"
	@echo "... players/MonteCarloPlayer.o"
	@echo "... players/MonteCarloPlayer.i"
	@echo "... players/MonteCarloPlayer.s"
	@echo "... players/RandomPlayer.o"
	@echo "... players/RandomPlayer.i"
	@echo "... players/RandomPlayer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

